[[headers]]
  for = "*.avif"
  [headers.values]
    Content-Type = "image/avif"
    Content-Disposition = "inline"

[[redirects]]
  from = "/talks/*"
  to = "https://mefody.github.io/talks/:splat"
  status = 301
